[2024-05-01T23:39:57.099-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T23:39:57.129-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica.read_players manual__2024-05-02T02:38:41.452837+00:00 [queued]>
[2024-05-01T23:39:57.144-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica.read_players manual__2024-05-02T02:38:41.452837+00:00 [queued]>
[2024-05-01T23:39:57.145-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T23:39:57.202-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_players> on 2024-05-02 02:38:41.452837+00:00
[2024-05-01T23:39:57.209-0300] {standard_task_runner.py:63} INFO - Started process 21838 to run task
[2024-05-01T23:39:57.219-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica', 'read_players', 'manual__2024-05-02T02:38:41.452837+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica.py', '--cfg-path', '/tmp/tmpas8q2bcx']
[2024-05-01T23:39:57.219-0300] {standard_task_runner.py:91} INFO - Job 94: Subtask read_players
[2024-05-01T23:39:57.309-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica.read_players manual__2024-05-02T02:38:41.452837+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-05-01T23:39:57.454-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica' AIRFLOW_CTX_TASK_ID='read_players' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T02:38:41.452837+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T02:38:41.452837+00:00'
[2024-05-01T23:39:57.456-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T23:39:57.467-0300] {postgres.py:175} INFO - Running copy expert: COPY (SELECT * FROM players) TO stdout WITH CSV HEADER, filename: /home/ath/projects/atividade_pratica_dags/data/players.csv
[2024-05-01T23:39:58.612-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T23:39:58.652-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/dags/atividade_pratica.py", line 37, in read_players_db
    pghook.copy_expert(
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 180, in copy_expert
    with open(filename, "r+") as file, closing(self.get_conn()) as conn, closing(conn.cursor()) as cur:
                                               ^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 131, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `PG_SWORDBLAST` isn't defined
[2024-05-01T23:39:58.679-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica, task_id=read_players, execution_date=20240502T023841, start_date=20240502T023957, end_date=20240502T023958
[2024-05-01T23:39:58.738-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task read_players (The conn_id `PG_SWORDBLAST` isn't defined; 21838)
[2024-05-01T23:39:58.798-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-01T23:39:58.815-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T23:39:58.816-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
