[2024-04-28T21:08:56.477-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:08:56.500-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:08:05.979845+00:00 [queued]>
[2024-04-28T21:08:56.511-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:08:05.979845+00:00 [queued]>
[2024-04-28T21:08:56.512-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:08:56.541-0300] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2024-04-29 00:08:05.979845+00:00
[2024-04-28T21:08:56.548-0300] {standard_task_runner.py:63} INFO - Started process 11627 to run task
[2024-04-28T21:08:56.553-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'decide_branch', 'manual__2024-04-29T00:08:05.979845+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpjtepr9gv']
[2024-04-28T21:08:56.553-0300] {standard_task_runner.py:91} INFO - Job 28: Subtask decide_branch
[2024-04-28T21:08:56.601-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.decide_branch manual__2024-04-29T00:08:05.979845+00:00 [running]> on host ath
[2024-04-28T21:08:56.682-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:08:05.979845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:08:05.979845+00:00'
[2024-04-28T21:08:56.683-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:08:56.683-0300] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-28T21:08:56.684-0300] {python.py:237} INFO - Done. Returned value was: path_does_not_exist
[2024-04-28T21:08:56.684-0300] {branch.py:36} INFO - Branch into path_does_not_exist
[2024-04-28T21:08:56.684-0300] {skipmixin.py:178} INFO - Following branch path_does_not_exist
[2024-04-28T21:08:56.685-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:08:56.703-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=atividade_pratica_dag, task_id=decide_branch, execution_date=20240429T000805, start_date=20240429T000856, end_date=20240429T000856
[2024-04-28T21:08:56.764-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-28T21:08:56.781-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:08:56.782-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
