[2024-04-30T22:05:58.369-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T22:05:58.384-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-05-01T01:04:50.604097+00:00 [queued]>
[2024-04-30T22:05:58.392-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.decide_branch manual__2024-05-01T01:04:50.604097+00:00 [queued]>
[2024-04-30T22:05:58.393-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T22:05:58.419-0300] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): decide_branch> on 2024-05-01 01:04:50.604097+00:00
[2024-04-30T22:05:58.428-0300] {standard_task_runner.py:63} INFO - Started process 36642 to run task
[2024-04-30T22:05:58.436-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'decide_branch', 'manual__2024-05-01T01:04:50.604097+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpv1oh7qcr']
[2024-04-30T22:05:58.437-0300] {standard_task_runner.py:91} INFO - Job 65: Subtask decide_branch
[2024-04-30T22:05:58.517-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.decide_branch manual__2024-05-01T01:04:50.604097+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-04-30T22:05:58.635-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='decide_branch' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T01:04:50.604097+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-01T01:04:50.604097+00:00'
[2024-04-30T22:05:58.636-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T22:05:58.637-0300] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-30T22:05:58.644-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T22:05:58.644-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/dags/atividade_pratica_dag.py", line 60, in path_exists
    file_path = ti.xcom_pull(task_ids="share_path_task", key="path") + "/data/path.txt"
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2024-04-30T22:05:58.661-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=decide_branch, execution_date=20240501T010450, start_date=20240501T010558, end_date=20240501T010558
[2024-04-30T22:05:58.850-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task decide_branch (unsupported operand type(s) for +: 'NoneType' and 'str'; 36642)
[2024-04-30T22:05:58.903-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T22:05:58.923-0300] {logging_mixin.py:188} WARNING - /home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-30T22:05:58.946-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T22:05:58.981-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
