[2024-04-30T19:20:08.464-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T19:20:08.733-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: check_file_dag.check_file_existence manual__2024-04-30T22:19:39.471143+00:00 [queued]>
[2024-04-30T19:20:08.763-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: check_file_dag.check_file_existence manual__2024-04-30T22:19:39.471143+00:00 [queued]>
[2024-04-30T19:20:08.764-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T19:20:08.880-0300] {taskinstance.py:2327} INFO - Executing <Task(FileSensor): check_file_existence> on 2024-04-30 22:19:39.471143+00:00
[2024-04-30T19:20:08.886-0300] {standard_task_runner.py:63} INFO - Started process 26908 to run task
[2024-04-30T19:20:08.894-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'check_file_dag', 'check_file_existence', 'manual__2024-04-30T22:19:39.471143+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/file_sensor_dag.py', '--cfg-path', '/tmp/tmpik7op0mq']
[2024-04-30T19:20:08.897-0300] {standard_task_runner.py:91} INFO - Job 61: Subtask check_file_existence
[2024-04-30T19:20:09.127-0300] {task_command.py:426} INFO - Running <TaskInstance: check_file_dag.check_file_existence manual__2024-04-30T22:19:39.471143+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-04-30T19:20:09.431-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='check_file_dag' AIRFLOW_CTX_TASK_ID='check_file_existence' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T22:19:39.471143+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T22:19:39.471143+00:00'
[2024-04-30T19:20:09.434-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T19:20:09.435-0300] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-04-30T19:20:09.450-0300] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-04-30T19:20:09.451-0300] {filesystem.py:85} INFO - Poking for file /home/ath/projects/atividade_pratica_dags/dags/ls_dag.py
[2024-04-30T19:20:09.451-0300] {filesystem.py:89} INFO - Found File /home/ath/projects/atividade_pratica_dags/dags/ls_dag.py last modified: 20240430020352
[2024-04-30T19:20:09.451-0300] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-30T19:20:09.452-0300] {filesystem.py:85} INFO - Poking for file /home/ath/projects/atividade_pratica_dags/dags/ls_dag.py
[2024-04-30T19:20:09.452-0300] {filesystem.py:89} INFO - Found File /home/ath/projects/atividade_pratica_dags/dags/ls_dag.py last modified: 20240430020352
[2024-04-30T19:20:09.452-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T19:20:09.463-0300] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=check_file_dag, task_id=check_file_existence, execution_date=20240430T221939, start_date=20240430T222008, end_date=20240430T222009
[2024-04-30T19:20:09.518-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-30T19:20:09.559-0300] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-30T19:20:09.595-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
