[2024-04-28T21:08:47.479-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-28T21:08:47.518-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica_dag.get_path manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:47.536-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica_dag.get_path manual__2024-04-29T00:07:07.430511+00:00 [queued]>
[2024-04-28T21:08:47.536-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-28T21:08:47.567-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): get_path> on 2024-04-29 00:07:07.430511+00:00
[2024-04-28T21:08:47.578-0300] {standard_task_runner.py:63} INFO - Started process 11614 to run task
[2024-04-28T21:08:47.584-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica_dag', 'get_path', 'manual__2024-04-29T00:07:07.430511+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica_dag.py', '--cfg-path', '/tmp/tmpeoesemqd']
[2024-04-28T21:08:47.585-0300] {standard_task_runner.py:91} INFO - Job 26: Subtask get_path
[2024-04-28T21:08:47.658-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica_dag.get_path manual__2024-04-29T00:07:07.430511+00:00 [running]> on host ath
[2024-04-28T21:08:47.740-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica_dag' AIRFLOW_CTX_TASK_ID='get_path' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T00:07:07.430511+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T00:07:07.430511+00:00'
[2024-04-28T21:08:47.741-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-28T21:08:47.742-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-28T21:08:47.743-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo $AIRFLOW_HOME  > data/path.txt']
[2024-04-28T21:08:47.757-0300] {subprocess.py:86} INFO - Output:
[2024-04-28T21:08:47.760-0300] {subprocess.py:93} INFO - /usr/bin/bash: linha 1: data/path.txt: Arquivo ou diret√≥rio inexistente
[2024-04-28T21:08:47.760-0300] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-28T21:08:47.761-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-28T21:08:47.771-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/athlon/projects/airflow/.venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-28T21:08:47.777-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica_dag, task_id=get_path, execution_date=20240429T000707, start_date=20240429T000847, end_date=20240429T000847
[2024-04-28T21:08:47.793-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task get_path (Bash command failed. The command returned a non-zero exit code 1.; 11614)
[2024-04-28T21:08:47.835-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-28T21:08:47.852-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-28T21:08:47.853-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
