[2024-05-02T00:05:07.217-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-02T00:05:07.262-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: atividade_pratica.read_players manual__2024-05-02T03:03:27.129053+00:00 [queued]>
[2024-05-02T00:05:07.277-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: atividade_pratica.read_players manual__2024-05-02T03:03:27.129053+00:00 [queued]>
[2024-05-02T00:05:07.277-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-02T00:05:07.317-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): read_players> on 2024-05-02 03:03:27.129053+00:00
[2024-05-02T00:05:07.327-0300] {standard_task_runner.py:63} INFO - Started process 23936 to run task
[2024-05-02T00:05:07.358-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'atividade_pratica', 'read_players', 'manual__2024-05-02T03:03:27.129053+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/atividade_pratica.py', '--cfg-path', '/tmp/tmp8xt3sv9o']
[2024-05-02T00:05:07.358-0300] {standard_task_runner.py:91} INFO - Job 99: Subtask read_players
[2024-05-02T00:05:07.629-0300] {task_command.py:426} INFO - Running <TaskInstance: atividade_pratica.read_players manual__2024-05-02T03:03:27.129053+00:00 [running]> on host xubuntu.myguest.virtualbox.org
[2024-05-02T00:05:08.601-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='atividade_pratica' AIRFLOW_CTX_TASK_ID='read_players' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T03:03:27.129053+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-02T03:03:27.129053+00:00'
[2024-05-02T00:05:08.633-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-02T00:05:08.689-0300] {postgres.py:175} INFO - Running copy expert: COPY (SELECT * FROM players) TO stdout WITH CSV HEADER, filename: /home/ath/projects/atividade_pratica_dags/data/players.csv
[2024-05-02T00:05:12.840-0300] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-05-02T00:05:12.893-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-02T00:05:12.895-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/dags/atividade_pratica.py", line 37, in read_players_db
    pghook.copy_expert(
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 180, in copy_expert
    with open(filename, "r+") as file, closing(self.get_conn()) as conn, closing(conn.cursor()) as cur:
                                               ^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ath/projects/atividade_pratica_dags/.venv/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution

[2024-05-02T00:05:12.983-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=atividade_pratica, task_id=read_players, execution_date=20240502T030327, start_date=20240502T030507, end_date=20240502T030512
[2024-05-02T00:05:13.104-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task read_players (could not translate host name "postgres" to address: Temporary failure in name resolution
; 23936)
[2024-05-02T00:05:13.193-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-02T00:05:13.242-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-02T00:05:13.245-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
